import json

from fastapi import APIRouter, Depends
from fastapi.responses import Response
from sqlalchemy import or_
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.database import get_session
from app.errors import NotFoundError
from app.models import Prophecy, Connection, AnalysisCache
from app.services.prompts import BOOK_NAMES

router = APIRouter(prefix="/api/v1/export", tags=["export"])


@router.get("/prophecy/{prophecy_id}")
async def export_prophecy(
    prophecy_id: int,
    session: AsyncSession = Depends(get_session),
):
    prophecy = await session.get(Prophecy, prophecy_id)
    if prophecy is None:
        raise NotFoundError(f"Prophecy with id {prophecy_id} not found")

    book_name = BOOK_NAMES.get(prophecy.source_book, f"Book {prophecy.source_book}")
    lines = [
        f"# {prophecy.title}",
        "",
        f"**Source:** {prophecy.source_character}, {prophecy.source_chapter} ({book_name})",
        f"**Type:** {prophecy.prophecy_type}",
        f"**Status:** {prophecy.status}",
        "",
        "## Description",
        "",
        prophecy.description,
        "",
    ]

    if prophecy.notes:
        lines.extend(["## Notes", "", prophecy.notes, ""])

    if prophecy.fulfillment_evidence:
        lines.extend(["## Fulfillment Evidence", "", prophecy.fulfillment_evidence, ""])

    if prophecy.subject_characters:
        lines.extend(["## Characters", "", ", ".join(prophecy.subject_characters), ""])

    if prophecy.keywords:
        lines.extend(["## Keywords", "", ", ".join(prophecy.keywords), ""])

    # Connections
    conn_result = await session.exec(
        select(Connection).where(
            or_(
                Connection.source_prophecy_id == prophecy_id,
                Connection.target_prophecy_id == prophecy_id,
            )
        )
    )
    connections = conn_result.all()

    if connections:
        lines.extend(["## Connections", ""])
        for conn in connections:
            connected_id = (
                conn.target_prophecy_id
                if conn.source_prophecy_id == prophecy_id
                else conn.source_prophecy_id
            )
            connected = await session.get(Prophecy, connected_id)
            title = connected.title if connected else f"Prophecy #{connected_id}"
            lines.extend([
                f"### {conn.connection_type.replace('_', ' ').title()} — {title}",
                f"**Confidence:** {conn.confidence:.0%}",
                "",
                f"**Evidence:** {conn.evidence}",
                "",
                f"**Implication:** {conn.implication}",
                "",
            ])

    # Cached prediction
    prediction_result = await session.exec(
        select(AnalysisCache).where(
            AnalysisCache.analysis_type == "prediction_single",
            AnalysisCache.input_summary == f"Prediction for: {prophecy.title}",
        )
    )
    prediction = prediction_result.first()
    if prediction:
        pred_data = json.loads(prediction.result_json)
        lines.extend(["## TWOW Prediction", "", pred_data.get("text", ""), ""])

    lines.extend([
        "---",
        "*Generated by Weirwood.net — ASOIAF Prophecy Tracker & Connection Engine*",
    ])

    markdown = "\n".join(lines)
    safe_title = prophecy.title.replace(" ", "_").replace("/", "_")

    return Response(
        content=markdown,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{safe_title}.md"'},
    )
